# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pr: none
trigger:
- master

resources:
- repo: self

name: $(majorVersion).$(minorVersion)$(Rev:.r)

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push an image
      inputs:
        containerRegistry: 'Hieu Tran Docker Hub'
        command: 'buildAndPush'
        dockerfile: '$(Build.SourcesDirectory)/HelenExpress.GraphQL/Dockerfile'
        repository: '$(dockerAccount)/helen-express-api'
        tags: '$(Build.BuildNumber)'
        buildContext: '$(System.DefaultWorkingDirectory)'
    - task: SendTelegramNotification@0
      inputs:
        botToken: '1179405965:AAG_WogLBlCYBCEjBudkSUI9xPl-y23tIVk'
